### ISSUE TITLE
Dark mode follow the system's

### ISSUE THREAD

**Issue by courrier1** [xiaoyifang/goldendict-ng#687] opened 2023-05-14 16:25 UTC
Make an option for the app to follow Windows' dark mode, it's a little bothersome to manually switch every time the dark/light mode is on.

**Comment by courrier1** [comment] 2023-07-21 17:41
bump

**Comment by loyukfai** [comment] 2023-08-13 18:55
Ditto

**Comment by xuangeyouneihan** [comment] 2023-11-07 14:00
So will this be added to the software?

**Comment by xuangeyouneihan** [comment] 2024-11-05 05:02
bump

**Comment by shenlebantongying** [comment] 2024-11-06 00:04
Duplicate of https://github.com/xiaoyifang/goldendict-ng/issues/1561

**Closed by shenlebantongying** 2024-11-06 00:04 UTC
