### ISSUE TITLE
Add word to favourite, `&` is prefixed

### ISSUE THREAD

**Issue by lengyijun** [xiaoyifang/goldendict-ng#1892] opened 2024-11-02 06:23 UTC
**Describe the bug**

Add words to favourite, some words are prefixed with `&`, while others doesn't

**To Reproduce**

**Affected Dictionaries**

Not sure

**Expected behavior**

**Screenshots**

https://github.com/user-attachments/assets/36993140-ad5b-481e-a656-4a98295d479b

**OS and software versions**

Goldendict-ng 24.09.0 at 2024-10-21T00:11:06Z
Qt 6.7.2 GCC 14.2.1 20240910 manjaro linux 6.6.54-2-MANJARO x86_64-little_endian-lp64
Flags: MAKE_ZIM_SUPPORT MAKE_CHINESE_CONVERSION_SUPPORT NO_TTS_SUPPORT no_ffmpeg_player

- OS: manjaro
- Version latest

**Additional context**

Platform | Context
---------|----------
 Windows |Upload the dmp file in the crash folder located in the configuration folder (can be opened through the menu help->configuration folder) to here
 Macos | upload the crashpad crash log
 Linux | gdb backtrace info

**Comment by shenlebantongying** [comment] 2024-11-02 08:35
Duplicate of https://github.com/xiaoyifang/goldendict-ng/issues/1484

The root issue is KDE sabotaging the tab widget. Though, GD storing state variables in UI widgets is somewhat a bad practice of programming.

**Comment by shenlebantongying** [comment] 2024-11-02 08:37
duplicate of https://github.com/xiaoyifang/goldendict-ng/issues/1484

**Comment by shenlebantongying** [comment] 2024-11-02 08:38
duplicate of https://github.com/xiaoyifang/goldendict-ng/issues/1484

**Closed by shenlebantongying** 2024-11-02 08:38 UTC
