### ISSUE TITLE
Get error msg "Invalid data found when processing input" When mouse hover on specified sound source.

### ISSUE THREAD

**Issue by zw963** [xiaoyifang/goldendict-ng#1707] opened 2024-07-24 10:45 UTC
Check following screenshot.

![image](https://github.com/user-attachments/assets/89ffc017-9175-4ce8-8caf-36bf243cf6d2)

When i mouse hover on the sound source except the first one, get error message as above.

错误消息出现时，仍然能够听到声音，但是伴随很嘈杂的噪音，很沙哑的那种，几乎不可用。

I thought this issue probably related to #1540 

Thanks.

Current used version:

goldendict-ng-git 24.05.13.r5565.06d4b62b-1 From Arch repo.

**Comment by xiaoyifang** [comment] 2024-07-25 02:44
右键保存 audio .然后用其他播放器看下是否能正常播放。

另外是所有的单词都这样，还是个别单词，如果是个别单词，不排除是词典本身的问题。

**Comment by zw963** [comment] 2024-07-25 10:01
> 右键保存 audio .然后用其他播放器看下是否能正常播放。
> 
> 另外是所有的单词都这样，还是个别单词，如果是个别单词，不排除是词典本身的问题。

因该是所有单词，只要这个单词存在如下截图的两个声音源，声音就会有问题。

![image](https://github.com/user-attachments/assets/4530ab7d-43f9-4b8e-bc39-2dc3bf7574c3)

我也上传了保存的声音文件到这里。

[sounds.tar.gz](https://github.com/user-attachments/files/16374057/sounds.tar.gz)

测试了下， vlc 可以正确播放没问题，mpv 播放时声音也很卡，和使用 goldendict 类似，goldendict 声音更差一些。

而且命令行播放时，输出好多错误。

```
 ╰─ $ mpv mediaenglishus_prontthithis_this__us_1.spx
 (+) Audio --aid=1 (speex 1ch 44100Hz)
AO: [pipewire] 44100Hz mono 1ch float
Error decoding audio.
Error decoding audio.

... 很多行一样的输出

Error decoding audio.
Error decoding audio.
A: 00:00:00 / 00:00:00 (70%)
Exiting... (End of file）
```

**Comment by xiaoyifang** [comment] 2024-07-26 00:25
词典的声音如果有问题的话，需要词典制作者处理了

**Comment by zw963** [comment] 2024-07-26 02:45
> 词典的声音如果有问题的话，需要词典制作者处理了

我不得不重新换回 goldendict-git, 因为：

1.  没有 #1540 这个问题，似乎 ng 很长时间了，一直解决不了。
2. 如果你说是辞典的问题，但是 goldendict-git 里面的默认 QT multimedia 却工作的很好。（ffmpeg + libao 似乎同样的问题）
3. 最重要的，之前升级系统后，因为 QT 版本问题不工作了，现在修复了。

所以，我猜上面的问题应该 ng 都是可以解决的，而不是词典制作者处理，毕竟这些词典我用挺久的了。

**Comment by shenlebantongying** [comment] 2024-07-26 05:26
The audio works fine on macOS version. Test dict with the speex in question [dsl.zip](https://github.com/user-attachments/files/16386866/dsl.zip)

I suspect this is a duplicate of <https://github.com/xiaoyifang/goldendict-ng/issues/1612>: In the newest FFmpeg (the one in Arch), speex supported has bug.

> default QT multimedia in goldendict-git works very well. (ffmpeg + libao seems to have the same problem)

In Qt5, the multimedia uses GStreamer backend by default, which also supports speex.


---

If this is the case, a workaround is simply replacing `qt6-multimedia-ffmpeg` with `qt6-multimedia-gstreamer` for now.

**Comment by xiaoyifang** [comment] 2024-07-26 05:44
> 2\. 如果你说是辞典的问题，但是 goldendict-git 里面的默认 QT multimedia 却工作的很好。

目前gd-ng用的也是qtmultimedia.   不过qtmultimedia 在qt6.5之后用的底层也是ffmpeg。

根本原因还是语音文件的问题，这种问题， gd-ng目前不会处理的。

**Comment by shenlebantongying** [comment] 2024-07-26 08:32
Workaround in my above comment.

Related FFmpeg ticket-> https://trac.ffmpeg.org/ticket/11054

**Closed by shenlebantongying** 2024-07-26 08:32 UTC

**Comment by zw963** [comment] 2024-07-27 06:49
> A workaround is simply replacing qt6-multimedia-ffmpeg with qt6-multimedia-gstreamer for now.

I found i can install both package on Arch,  they are not mutually exclusive.

```
 ╰─ $ pacman -Q |grep qt6-multimedia
qt6-multimedia 6.7.2-1
qt6-multimedia-ffmpeg 6.7.2-1
qt6-multimedia-gstreamer 6.7.2-1
```

**Comment by shenlebantongying** [comment] 2024-07-27 07:02
Just uninstall one, or select a backend by setting env variable `QT_MEDIA_BACKEND` to `gstreamer`.

https://doc.qt.io/qt-6/qtmultimedia-index.html#changing-backends

**Comment by escape0707** [comment] 2024-08-21 14:39
Yes. When I only install qt6-multimedia-gstreamer, and sue Qt Multimedia in goldendict-ng, the software won't pronounce anymore. I'll stick to use mplayer for the moment.

**Comment by shenlebantongying** [comment] 2024-11-07 21:25
Duplicate of https://github.com/xiaoyifang/goldendict-ng/issues/1738
