### ISSUE TITLE
Every upgrade of the Mac version will invalidate the word retrieval hotkey

### ISSUE THREAD

**Issue by yshumy** [xiaoyifang/goldendict-ng#951] opened 2023-07-09 05:56 UTC
每次升级都会使取词热键失效，必须重新在辅助功能中添加才能重新生效。
<img width="588" alt="截屏2023-07-09 13 50 14" src="https://github.com/xiaoyifang/goldendict-ng/assets/103359913/99c3c0c3-a1db-48bd-ac78-85c6c5528ba2">
<img width="415" alt="截屏2023-07-09 13 52 35" src="https://github.com/xiaoyifang/goldendict-ng/assets/103359913/d1ec4277-c4b9-4bce-a36c-56f1ecb5e26b">

**Comment by shenlebantongying** [comment] 2023-08-06 06:26
Duplicate of #1046

**Closed by shenlebantongying** 2023-08-06 06:26 UTC
Labels: macOS
