### ISSUE TITLE
I can't copy a selected text while goldendict is open

### ISSUE THREAD

**Issue by sonerfromnurland** [xiaoyifang/goldendict-ng#630] opened 2023-04-30 16:07 UTC
On mac, I can't copy a selected text while goldendict is open by the known shortcut which Command+C. I need to quit the app to copy it. However, double C letters remember old copied text.

Goldendict 23.04.02-QingmingFestival.230402.ce9436f9
macos darwin 22.4.0 Qt 6.4.3 arm64-little_endian-lp64
Clang 13.0.0 (clang-1300.0.29.30)
Flags: MAKE_ZIM_SUPPORT MAKE_CHINESE_CONVERSION_SUPPORT

![2023-04-30 19 06 21](https://user-images.githubusercontent.com/99599870/235363669-e808a64a-80d7-4a7c-9823-ed5b416b4afb.gif)

**Comment by shenlebantongying** [comment] 2023-04-30 17:44
Disable the shortcut "Ctrl+C+C"

**Comment by itkind** [comment] 2023-06-07 19:10
Settings>Privacy & Security>Accessibility> remove GD from the list by clicking on the minus and add it again by clicking on the plus.

**Comment by ElhemEnohpi** [comment] 2023-09-08 12:57
Duplicate of #325. Removing and re-adding GD from Accessibility may or may not work. You can use a different hotkey, or disable it.

**Comment by shenlebantongying** [comment] 2024-10-09 01:44
Duplicate of https://github.com/xiaoyifang/goldendict-ng/issues/325

**Closed by shenlebantongying** 2024-10-09 01:44 UTC
Labels: macOS
