### ISSUE TITLE
Always on dock issue

### ISSUE THREAD

**Issue by sonerfromnurland** [xiaoyifang/goldendict-ng#583] opened 2023-04-26 20:19 UTC
I'm using goldendict on mac with the version I specify below. The issue for me is that it is seen always on dock.
It is a bit annoying. I tried to play with Info.plist file of it to hide it as written here, https://discussions.apple.com/thread/7444141 but GoldenDict cannot grab texts at all. How can I hide the icon?

<img width="778" alt="2023-04-26_22-59-21" src="https://user-images.githubusercontent.com/99599870/234692695-9e3bde71-6a05-42a1-b31f-810f089bc853.png">

Version info: version 23.04.02-QingmingFestival.230402.ce9436f9
 Based on Qt 6.4.3 (Clang 13.0.0 (clang-1300.0.29.30, 64 bit)

**Comment by shenlebantongying** [comment] 2023-04-27 03:33
Your problem is the duplication of "Tray icon" and "Dock icon". Someone else also complains about it.

I think we should remove the tray icon from macOS version, and give the tray icon's menu to the dock icon.

https://github.com/goldendict/goldendict/issues/1356#issuecomment-1362735547 

---

On MacOS, a process with GUI must have a dock icon. 

Declaring a process as "UIElement" will hide the dock icon but allow the tray icon. However, it has unknown consequences, as you said one possible bug `play with Info.plist file of it to hide it as written here, but GoldenDict cannot grab texts at all`

----

This is what I learned when trying to fix https://github.com/goldendict/goldendict/issues/1356

We can hide the dock icon programmatically with `TransformProcessType` 

* https://developer.apple.com/documentation/applicationservices/1462420-transformprocesstype?language=objc
* https://stackoverflow.com/a/54501219/12494649

The problem is that there is almost no documentation about the implications of changing process type. 

Apple's doc are too cryptical:

https://developer.apple.com/documentation/applicationservices/1501117-anonymous/kprocesstransformtouielementapplication 

https://developer.apple.com/documentation/bundleresources/information_property_list/lsuielement?language=objc

https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/20001431-108256

We need a macOS expert help or someone do extensive poking around those behaviours.

The red "close" button is still somehow broken (close it to tray icon, and it cannot be brought back via dock icon) for the similar reason that macOS will display a dock icon for any running GUI process.

I think removing the tray icon from macOS and turning the dock icon into the old tray icon is the most practical approach. (Set dock icon menu is easy https://doc.qt.io/qt-6/qmenu.html#setAsDockMenu)

**Comment by shenlebantongying** [comment] 2023-04-27 03:39
Philosophically, Apple wants apps with a main window to always have an accessible dock icon.

Tray icons are only for background-only-ish apps. GD is not strictly that kind.

**Closed** 2024-11-11 07:32 UTC
Labels: macOS
