### ISSUE TITLE
You cannot select all the pictures in the dictionary and copy and paste them, you can only copy them one by one. Is it possible to copy and paste all selected text?

### ISSUE THREAD

**Issue by yshumy** [xiaoyifang/goldendict-ng#1557] opened 2024-06-11 16:01 UTC
技术上可能吗？

**Comment by shenlebantongying** [comment] 2024-06-11 23:26
duplicate of https://github.com/xiaoyifang/goldendict-ng/issues/1460

**Closed by shenlebantongying** 2024-06-11 23:26 UTC
