### ISSUE TITLE
The audio player comes back up, but then fails after a while.

### ISSUE THREAD

**Issue by yshumy** [xiaoyifang/goldendict-ng#1181] opened 2023-09-28 12:14 UTC
需要重启软件才能恢复音频播放。

**Comment by xiaoyifang** [comment] 2023-09-28 12:48
具体一点

**Comment by yshumy** [comment] 2023-09-29 01:13
> 具体一点

Mac，前几版都不能播放音频，现在最新版可以播放了，但是，软件打开后刚开始可以播放，等一两个小时后，又不能播放了，需要重启软件才能恢复正常播放。

**Comment by BEST8OY** [comment] 2023-09-29 18:54
> You need to restart the software to resume normal playback.

Same on Windows 11.

**Comment by BEST8OY** [comment] 2023-09-30 14:56
> > You need to restart the software to resume normal playback.
> 
> There is another issue. (Windows 11) If you open GD (new instance) with jack 3.5 plugged and then unplug it there is no sound from system speaker If you open GD (new instance) with system speaker and then plug 3.5 jack the sound will play from system speaker

@xiaoyifang 
Okay this one is fixed in latest version.
But why did interface font become so small?
And if possible, bring back black window frame which white now!
![image](https://github.com/xiaoyifang/goldendict-ng/assets/70865987/fd804fd5-5170-430d-9f82-d0cbc344108c)

**Comment by shenlebantongying** [comment] 2024-10-15 06:06
duplicate of https://github.com/xiaoyifang/goldendict-ng/issues/1297

**Closed by shenlebantongying** 2024-10-15 06:06 UTC
