### ISSUE TITLE
Qt6.x Appimage failed to run.

### ISSUE THREAD

**Issue by atauzki** [xiaoyifang/goldendict-ng#1244] opened 2023-10-16 05:16 UTC
**Describe the bug**
OS: Ubuntu 20.04
commit ID: 743226e

**To Reproduce**
1. download qt6.5.2 appimage file and chmod +x
2. open it with the shell command with the default dictionaries. (No any additional dicts loaded) 
3. enter some words 
4. crash

that's the log.
```
No favorites file found
Load done

starting create the fts with thread: 3
waiting for all the fts creation to finish.
finished/cancel all the fts creation
reset inspector
getResource: "gdlookup://localhost?word=Welcome!&group=4294967295&word=&group=0"
scheme: "gdlookup"
host: "localhost"
In-place finish.

====reading  3424 of (3424) bytes . Finished: 1
article view loaded url: "data:text/html;charset=UTF-8,%3C%21DOCTYPE html%3E%0A%3Chtml%3E%3Chead%3E%0A%3Cmeta charset%3D%22utf-8%22%3E%0A%3Cscript src%3D%22qrc%3A%2F%2F%2Fscripts%2Fjquery-3.6.0.slim.min.js%22%3E%3C%2Fscript%3E" true
article view loaded url: "gdlookup://localhost/?word=Welcome!&group=4294967295" true
wiki request begin

wiki request begin

cancel the request
cancel the request
request end

request end

"Prefix find in \"dict.org\" fault: Data reading error: socket error 5: \"Network operation timed out\"\n"
wiki request begin

wiki request begin

cancel the request
cancel the request
cancel the request
cancel the request
request end

request end

wiki request begin

wiki request begin

getResource: "gdlookup://localhost?word=test&group=4294967294&word=&group=0"
scheme: "gdlookup"
host: "localhost"
clear current dictionaries: "test"
MediaWiki: requesting article test

MediaWiki: requesting article test

some body finished
one not finished.
====reading  1424 of (1424) bytes . Finished: 0
====reading  0 of (1424) bytes . Finished: 0
====reading  0 of (1424) bytes . Finished: 0
matches 0
done.

Finished.

Finished.

matches 0
done.

Finished.

Finished.

Finished.

MediaWiki: generating table of contents from the sections element.
done.

Finished.

some body finished
one finished.
erasing..
erase done..
one not finished.
send dicts(updated): "groupId:4294967294,word:test,dictId:ae6f89aac7151829681b85f035d54e48"
receive dicts, current word: "test" "test" : QList("ae6f89aac7151829681b85f035d54e48")
====reading  15693 of (17117) bytes . Finished: 0
====reading  0 of (17117) bytes . Finished: 0
getResource: "gico://ae6f89aac7151829681b85f035d54e48/dicticon.png"
scheme: "gico"
host: "ae6f89aac7151829681b85f035d54e48"
[248804:248842:1016/131303.178774:ERROR:nss_util.cc(232)] Error initializing NSS with a persistent database (sql:/home/wz/.pki/nssdb): libsoftokn3.so: 无法打开共享对象文件: 没有那个文件或目录
[248804:248842:1016/131303.178829:ERROR:nss_util.cc(124)] Error initializing NSS without a persistent database: NSS error code: -5925
[248804:248842:1016/131303.178835:FATAL:nss_util.cc(126)] nss_error=-5925, os_error=0
追踪与中断点陷阱

```
but related deb `libnss3` has already installed on my system.

5. qt6.6.0 doesn't start, related log:
```
qt.multimedia.ffmpeg.libsymbolsresolver: Couldn't load VAAPI library
[1016/131536.614333:FATAL:v8_initializer.cc(516)] Error loading V8 startup snapshot file
[1016/131536.615078:FATAL:v8_initializer.cc(516)] Error loading V8 startup snapshot file
追踪与中断点陷阱
```
Core dump files:
[core-6.5.2.gz](https://github.com/xiaoyifang/goldendict-ng/files/12912466/core-6.5.2.gz)
[core-6.6.0.gz](https://github.com/xiaoyifang/goldendict-ng/files/12912473/core-6.6.0.gz)

**Comment by xiaoyifang** [comment] 2023-10-16 05:38
https://forum.qt.io/topic/150877/qt-multimedia-warnings-qt-6-6-0/3

libva?

**Comment by atauzki** [comment] 2023-10-16 05:40
> https://forum.qt.io/topic/150877/qt-multimedia-warnings-qt-6-6-0/3
> 
> libva?

install `libva-dev`, and the followed two messages still exists.

**Comment by xiaoyifang** [comment] 2023-10-16 05:45
seems suddenly the error take place.



> zing NSS with a persistent database (sql:/home/wz/.pki/nssdb): libsoftokn3.so

this? 

https://github.com/probonopd/linuxdeployqt/issues/35

@atauzki  can you try this or build from source 
https://flathub.org/zh-Hans/apps/io.github.xiaoyifang.goldendict_ng

**Comment by atauzki** [comment] 2023-10-16 05:56
It works, but the text input reaction is very slow.

**Comment by xiaoyifang** [comment] 2023-10-16 06:05
possible, maybe the suggestion word list request cost some time.

The suggestion list should not affect the normal input process,
I'll see what I can do later.

**Comment by xiaoyifang** [comment] 2023-10-16 06:07
Wikipedia website?

**Comment by atauzki** [comment] 2023-10-16 06:09
It should be dict.org.

**Comment by atauzki** [comment] 2023-10-16 06:11
It must be dict.org. I use wikipedia behind the proxy and it doesn't block my input.

**Comment by xiaoyifang** [comment] 2023-10-16 06:34
dict.org problem should be fixed in this commit https://github.com/xiaoyifang/goldendict-ng/commit/743226e5147e7dd3974a61df3c3f13d544f6e9ed

flatpak is not up to date

**Comment by shenlebantongying** [comment] 2023-10-16 07:45
Just FYI about appimage issue:

> error initializing NSS with a persistent database (sql:/home/wz/.pki/nssdb):

This is a known issue of libNSS https://github.com/AppImageCommunity/pkg2appimage/blob/e87e6be17cc220b3e3b5e2eb0a108c0d2baca32c/excludelist#L200-L208

The implementation details of libNSS changed sometime in the past. The newer chromium inside Qt Webengine assumes newer libNSS implementation.

This is related to the fundamental flaw of AppImage: It assumes a "base Linux" that provides basic and fundamental things, and AppImage also assumes they won't change. However, "base Linux" does change, like this libNSS, and the assumptions of appimage just break. See how "base Linux" assumed by appimage is broken https://gitlab.com/probono/platformissues and there is a section for libNSS https://gitlab.com/probono/platformissues#nss

There are solutions by reading through appimage's issues related to libNSS, but I think are just hacks that accidentally work on certain but not all situations.

**Comment by shenlebantongying** [comment] 2023-10-16 07:45
Maybe we should recommend flatpak as the primary method for arbitrary Linux distros. Then build appimage on ubunt23.04 (which prevents it from running on ubuntu20.04) and put a notice that appimage only works on ubuntu23.04+ or equivalents (but this nullifies the purpose of appimage, aka running on older systems.).

**Comment by xiaoyifang** [comment] 2023-10-16 08:40
how do you configure the dict.org dictionary,

This is a little weird ,how does the background task affect the UI ?

**Comment by atauzki** [comment] 2023-10-16 08:48
No any configuration except the proxy.

**Comment by xiaoyifang** [comment] 2023-10-16 10:34
> Maybe we should recommend flatpak as the primary method for arbitrary Linux distros.

We can.


appimage always fails in some way.   Though it can still be offered for download ,but we can downgrade the importance of appimage and emergency of bug fix.

**Comment by xiaoyifang** [comment] 2023-10-17 01:34
> It must be dict.org. I use wikipedia behind the proxy and it doesn't block my input.

https://github.com/xiaoyifang/goldendict-ng/blob/f0dcc362fa91a05df0efad2ca17210c72b2f7a3b/src/dict/dictserver.cc#L66

seems caused by this line.
The weird place is that this function is invoked from the qtconcurrent already?

maybe rewrite the whole logic in asyncronous(nonblock) signal .

**Comment by xiaoyifang** [comment] 2023-10-29 07:32
https://github.com/xiaoyifang/goldendict-ng/pull/1264

**Comment by atauzki** [comment] 2023-10-31 04:15
dict.org still blocks user input in the latest scommitbranch commit.

**Comment by xiaoyifang** [comment] 2023-10-31 05:37
I know, This has not been fixed yet.

**Closed** 2023-11-01 00:07 UTC
Labels: AppImage
