### ISSUE TITLE
Playing sounds causes JS scripts to stop running

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [xiaoyifang/goldendict-ng#1839] opened 2024-10-19 16:17 UTC
**Describe the bug**

When the script on the page has not finished running, if you click the phonetic symbol to play the pronunciation, the remaining code in the script will not continue to run.
For example, the floating window of `LDOCE5++V 2-15` will not be displayed, the simplify mode of `OALD 2023.09` will not take effect, and various folded areas cannot be expanded.

**To Reproduce**
If there are more dictionaries loaded, the scripts will take longer to run and will be easier to reproduce.

**Affected Dictionaries**

ALL Dictionaries

**Expected behavior**

**Screenshots**

**OS and software versions**

Goldendict-ng 24.09.0.316ec900 at 2024-09-15T14:12:19Z
Qt 6.7.2 Visual C++ Compiler 194134120 windows winnt 10.0.22000 x86_64-little_endian-llp64
Flags: MAKE_ZIM_SUPPORT MAKE_CHINESE_CONVERSION_SUPPORT NO_TTS_SUPPORT no_ffmpeg_player

- OS: Windows11
- Version  21H2

**Additional context**

**Comment by shenlebantongying** [comment] 2024-10-21 03:08
Duplicate of https://github.com/xiaoyifang/goldendict-ng/issues/1379

**Closed by shenlebantongying** 2024-10-21 03:08 UTC
Labels: web/javascript
