### ISSUE TITLE
[Feature Request] GoldenDict as API Server

### ISSUE THREAD

**Issue by intzaaa** [xiaoyifang/goldendict-ng#1741] opened 2024-09-02 02:27 UTC
Currently, GoldenDict is a desktop software that integrates front-end and back-end. If GoldenDict can separate the front-end and back-end and provide a separate API server, it will provide many conveniences for front-end developers on different platforms, and may get rid of QT and derive mobile versions and web versions of GoldenDict, greatly enriching the ecology of GoldenDict.

**Comment by shenlebantongying** [comment] 2024-09-02 15:31
Sounds good, but it requires lots of time :)

Duplicate of https://github.com/xiaoyifang/goldendict-ng/issues/229

Duplicate of https://github.com/xiaoyifang/goldendict-ng/issues/905

**Closed by shenlebantongying** 2024-09-02 15:31 UTC

**Comment by KonstantinDjairo** [comment] 2024-09-26 20:34
> Duplicate of #229
> 
> Duplicate of #905
> 
> Sounds good, but battling with existing code requires lots of time :)

it's good to keep alternatives while keeping the existing qt frontend
