### ISSUE TITLE
Shows two application icons when started on fedora 40 with rpm package.

### ISSUE THREAD

**Issue by dc-me** [xiaoyifang/goldendict-ng#1828] opened 2024-10-16 14:08 UTC
**Describe the bug**
![Screenshot from 2024-10-16 07-07-36](https://github.com/user-attachments/assets/5676ebdb-5d04-4bb2-881d-c6800ad05e88)

**To Reproduce**
open the application it opens a new icon and shows the window.

**Affected Dictionaries**

If certain dictionaries don't work, list their names and types.

If possible, please attach the dictionary files or provide a downloadable link. (GitHub allows uploading 25MiB zip file as attachment)

**Expected behavior**
The goldendict icon should be active and shows the window.

**Screenshots**

**OS and software versions**

Copy & paste `help` -> `about` -> `Copy version info` to here

- OS: [e.g. Windows10,  Fedora37]

**Additional context**

Platform | Context
---------|----------
 Windows |Upload the dmp file in the crash folder located in the configuration folder (can be opened through the menu help->configuration folder) to here
 Macos | upload the crashpad crash log
 Linux | gdb backtrace info

**Comment by shenlebantongying** [comment] 2024-10-16 15:19
This was fixed by https://github.com/xiaoyifang/goldendict-ng/pull/1534

The fedora version is not updated to the current release version. You can manually edit the `.desktop` file to fix it immediately.

**Closed by shenlebantongying** 2024-10-16 15:19 UTC

**Comment by dc-me** [comment] 2024-10-16 21:14
Thank you for the quick response, but after I changed the .desktop file, ctrl + c +c doesn't work now. Any idea when the new version will be pushed to the fedora repository?

**Comment by shenlebantongying** [comment] 2024-10-16 21:28
I am not sure, but I don't think 'ctrl + c +c' is caused by editing the . desktop file. The shortcut doesn't work in newer Wayland environments.

**Comment by dc-me** [comment] 2024-10-16 21:31
Maybe changing the .desktop file caused it to run in Wayland. before it works

**Comment by dc-me** [comment] 2024-10-16 23:25
You are right, ctrl + c + c doesn't work on Wayland applications, It has nothing to do with .desktop file.
