### ISSUE TITLE
Arm support of mac

### ISSUE THREAD

**Issue by sonerfromnurland** [xiaoyifang/goldendict-ng#999] opened 2023-07-24 15:37 UTC
- I don't understand what's wrong with arm versions of mac? 
- When do you plan to share them again? 
- What's now latest arm version supported goldendict? 
- Can you share its release link please?

**Comment by shenlebantongying** [comment] 2023-07-25 01:27
Duplicate of https://github.com/xiaoyifang/goldendict-ng/issues/467

Needs Github makes arm github action runners available https://github.com/github/roadmap/issues/528

This is the last macOS universal build https://github.com/xiaoyifang/goldendict-ng/releases?q=wuyi&expanded=true

**Comment by sonerfromnurland** [comment] 2023-09-27 09:40
Do we have to wait more? There are lots of updates done in intel versions, but ARM. At least, could you release for ARM updated?

**Comment by shenlebantongying** [comment] 2023-09-27 18:57
Sadly, Yes, github action still don't have Arm mac runners.

No, I don't have enough time to do that.

---

However, you can try to install XCode, homebrew & some dependencies then build from source https://xiaoyifang.github.io/goldendict-ng/howto/build_from_source/#cmake-build

There will be a native `goldendict.app` with dependencies point to homebrew's location. It will work locally (via `open ./build_dir/goldendict.app`). Note that making it work on other people's machine is much harder, you need to bundling libraries and signing it.........

**Comment by sonerfromnurland** [comment] 2023-12-05 18:06
It seems now github supports mac silicon runnning. However, it seems a bit pricy. Do you think to get some donations?

**Comment by itkind** [comment] 2024-01-08 21:47
Any progress on this?

**Comment by xiaoyifang** [comment] 2024-01-19 16:14
https://github.com/xiaoyifang/goldendict-ng/pull/1367

https://github.com/xiaoyifang/goldendict-ng/issues/842

supported now.

**Closed by xiaoyifang** 2024-01-19 16:14 UTC
Labels: in future, macOS
