### ISSUE TITLE
Hiding dock icon on MacOS

### ISSUE THREAD

**Issue by sonerfromnurland** [xiaoyifang/goldendict-ng#1475] opened 2024-04-18 22:32 UTC
Is there any way or option to hide the dock icon of goldendict on mac os? It is a bit annoying as seen on the below image.

![Screenshot 2024-04-19 at 01 30 57](https://github.com/xiaoyifang/goldendict-ng/assets/99599870/2620bfca-7a98-457c-895a-39b58ae806b2)

For example this app has the feature
https://github.com/AppHouseKitchen/AlDente-Charge-Limiter

<img width="867" alt="image" src="https://github.com/xiaoyifang/goldendict-ng/assets/99599870/83af6b81-e84d-4482-9bd4-2488369aec1d">

**Comment by shenlebantongying** [comment] 2024-05-03 20:14
If your problem is duplication of icons on Tray and Dock, I want to work on the opposite direction:

On macOS, only have dock icon and remove Tray icon

https://github.com/goldendict/goldendict/issues/1356#issuecomment-1362735547

It will also fix the last bit of weirdness of "close" button https://github.com/xiaoyifang/goldendict-ng/issues/857

**Comment by sonerfromnurland** [comment] 2024-06-12 15:29
> If your problem is duplication of icons on Tray and Dock, I want to work on the opposite direction:
> 
> On macOS, only have dock icon and remove Tray icon
> 
> [goldendict/goldendict#1356 (comment)](https://github.com/goldendict/goldendict/issues/1356#issuecomment-1362735547)
> 
> It will also fix the last bit of weirdness of "close" button #857

Why not remove the dock icon instead of the tray icon? @shenlebantongying ?

**Comment by shenlebantongying** [comment] 2024-06-18 02:26
Duplicate of #583

**Closed by shenlebantongying** 2024-06-18 02:26 UTC
Labels: macOS
