### ISSUE TITLE
Quit when loading the webpage

### ISSUE THREAD

**Issue by GrimPixel** [xiaoyifang/goldendict-ng#1098] opened 2023-08-28 15:30 UTC
**Describe the bug**
It quits when loading the page

**To Reproduce**
1. search a word
2. see the error

**Expected behavior**
Webpage shows up.

**OS and software versions**

Copy & paste `help` -> `about` -> `Copy version info` to here

- OS: Manjaro Linux
- Version 6.5.2-GoldenDict-ng-x86_64.AppImage

**Additional context**
Linux:
```
GNU gdb (GDB) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
backtrace: No such file or directory.
```

**Comment by xiaoyifang** [comment] 2023-08-28 15:53
from the above error log ,I think it is a duplicate of #1097

**Comment by GrimPixel** [comment] 2023-08-28 18:49
The Debian FTP address required in AUR is unavailable now.

**Comment by GrimPixel** [comment] 2023-08-28 18:54
Yes, they looks similar.
I searched something with Wikipedia and Wiktionary disabled, only leaving dict.org active. It doesn't quit this time.

**Comment by xiaoyifang** [comment] 2023-08-29 01:30
https://github.com/AppImage/AppImageKit/issues/1004

**Comment by GrimPixel** [comment] 2023-08-29 11:53
My comment about “Debian FTP address” was replied to the wrong repository.
The AUR version runs well.

**Closed** 2023-08-31 08:00 UTC
Labels: AppImage
